rebar3 escriptize
./_build/default/bin/chorer ./examples/hello/hello.erl greet examples/hello
./_build/default/bin/chorer ./examples/async/simple.erl main examples/async
./_build/default/bin/chorer ./examples/ticktackstop/tictacstop.erl start examples/ticktackstop
./_build/default/bin/chorer ./examples/ticktackloop/tictacloop.erl start examples/ticktackloop
./_build/default/bin/chorer ./examples/customer/customer.erl main examples/customer
./_build/default/bin/chorer ./examples/serverclient/serverclient.erl main examples/serverclient
./_build/default/bin/chorer ./examples/trick/trick.erl main examples/trick
./_build/default/bin/chorer ./examples/airline/airline.erl main examples/airline
./_build/default/bin/chorer ./examples/conditional-case/conditional_case.erl main examples/conditional-case
./_build/default/bin/chorer ./examples/for-loop-recursion/forloop.erl main examples/for-loop-recursion
./_build/default/bin/chorer ./examples/function-call/funny.erl main examples/function-call
./_build/default/bin/chorer ./examples/high-order-fun/hof.erl greet examples/high-order-fun
./_build/default/bin/chorer ./examples/if-cases/ifcases.erl main examples/if-cases
./_build/default/bin/chorer ./examples/test/barber/barber.erl test examples/test/barber
./_build/default/bin/chorer ./examples/test/foo1/foo1.erl test examples/test/foo1
./_build/default/bin/chorer ./examples/test/foo2/foo2.erl test examples/test/foo2
./_build/default/bin/chorer ./examples/test/foo3/foo3.erl test examples/test/foo3
./_build/default/bin/chorer ./examples/test/foo4/foo4.erl test examples/test/foo4
./_build/default/bin/chorer ./examples/test/foo5/foo5.erl test examples/test/foo5
./_build/default/bin/chorer ./examples/test/foo6/foo6.erl test examples/test/foo6
./_build/default/bin/chorer ./examples/test/ping/ping.erl test examples/test/ping