name: gendocs

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-20.04
    name: Generate documentation
    strategy:
      matrix:
        otp: ['26']
        rebar3: ['3.22']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Run script
        run: rebar3 compile && rebar3 ex_doc --output build && cp -r assets build/assets

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
  deploy:
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4